# Config file for automatic testing at travis-ci.org

language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.4
          env: TOXENV=py34
        - os: linux
          sudo: required
          python: 3.5
          env: TOXENV=py35
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py36

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
#script: python3 setup.py test
script: coverage3 run setup.py test

# Command for online test coverage analysis
before_install:
     #Linux
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
     then pip install codecov ; fi
     #Get Version

     #osx
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade python ; fi   
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo easy_install pip ; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip install codecov ; fi
  
after_success:
  codecov
